version: "3.8"

services:
  dogecoin:
    image: xanimo/dogecoin:1.14.7
    volumes:
    - /mnt/volumes/core:/home/dogecoin/.dogecoin
    restart: unless-stopped
    env_file:
      - ./docker/1.14.7/bullseye/.env
  app:
    image: xanimo/lern-jwt
    depends_on:
      - dogecoin
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file: .env
