#!/bin/bash

npm run clean
npm run ssl
./internals/scripts/setenv.sh
npm run setup
npm run build

if docker image inspect xanimo/dogecoin:1.14.7 | grep -o '"RepoTags":'; then
    echo true
else
    pushd ./docker/
        ./build
    popd
fi

if [ ! -d "./data/users" ]; then
    mkdir -p ./data/users
fi

docker build --no-cache -t xanimo/lern-jwt -f Dockerfile.api .
