#!/bin/bash

if docker inspect lern-jwt | grep -o '"Status":'; then
    echo true
    docker stop lern-jwt
    docker rm lern-jwt
fi

if docker inspect dogecoin | grep -o '"Status":'; then
    echo true
    docker stop dogecoin
    docker rm dogecoin
fi

if docker network inspect dogecoin | grep -o "\[\]"; then
    docker network create dogecoin
fi

docker run -it --restart=always -d --network=dogecoin -v /mnt/volumes/core:/home/dogecoin/.dogecoin --name dogecoin -t xanimo/dogecoin:1.14.7
docker run -it --privileged --restart=always -d --network=dogecoin -v /var/run/docker.sock:/var/run/docker.sock -p 3001:3001 --name lern-jwt -t xanimo/lern-jwt
sleep 5
docker exec -it lern-jwt cat .env > .env
